### ISSUE TITLE
Could you add more details to the documentation?

### ISSUE THREAD

**Issue by jpalanco** [creatorKoo/bitwarden-iterm-helper#1]
I tried to do it, but I wasn't able to. Maybe with some screenshots, it will be easier, because it's a bit confusing.

What is <your_bitwarden_item_name>? Is the entry name at bitwarden? Does that mean I only can autocomplete one password?

Maybe <your_bitwarden_item_name> is a keyword I have to use.... Is <your_bitwarden_item> another keyword?

In the triggers, after selecting "Open Password Manager" I can't choose anything in Parameters, the dropdown is not populated.

Is not necessary to add anything to the PATH? When I open the profile I get an error at line 5 of unlock.sh saying that bw was not found. But I installed using brew, so it is installed for sure, and using the regular Term, it works.

Thank you for the helper! I wish I can use it soon

**Comment by creatorKoo** [comment]
I updated readme document with image. 
I wish this help to set up.

Each bitwarden item have one server info. and Each iTerm2's profile do auto-connect and auto-fill one server using one bitwarden item name.

Please let me know if you have any problems after reading updated readme(main page) again.

**Comment by jpalanco** [comment]
It is very clear now, thanks!
